### PR TITLE
fix master send old log that the log version is equal to metalogger l…

### PR DESCRIPTION
**Pull request by yinjiawind**
…astlogversion, it should be bigger than lastlogversion

### CODE REVIEW

**Comment by oxide94** [comment]
Hi,

thanks for your contributions!
We'll review them most probably next week.

Thanks,
Peter / MooseFS Team

**Comment by oxide94** [comment]
Hi @yinjiawind, as @acid-maker wrote, we included your one change which could be merged in commit 6c6ceec. Two other changes was rewritten with info "inspired by yinjiawind" in commit messages (commits: b99ce6e and fe7eb41). Thanks for your contributions!

Peter / MooseFS Team

**Comment by oxide94** [comment]
@yinjiawind By the way - please check your Git configuration, because it looks like you have wrong e-mail address in `~/.gitconfig` (and it was saved in your commit), look:

screen shot 2016-12-01 at 3 56 42 pm

Best regards,
Peter / MooseFS Team

**Comment by yinjiawind** [comment]
Thank you. 
I have changed it.

**Pull request closed without merging**
